### PR TITLE
Update ProjectList.md

### PR DESCRIPTION
**Pull request by yashaswi2000**
added OSS website repository to the projects list.

### CODE REVIEW

**Comment by hershd23** [comment]
Hi, @yashaswi2000 I was thinking of separating the website into a different section with the heading Web Projects. Do that and I'll merge it

**Comment by yashaswi2000** [comment]
Sure @hershd23, I will do that.

**Comment by yashaswi2000** [comment]
@hershd23 i have updated the projects list as you have mentioned, pls take a look.

**Review by hershd23 — APPROVED** [review]
LGTM!

**Pull request merged**
